window.onload=function(){
		Ajax.init({
		url:"http://localhost:8080/AjaxCROSTest/data.json",
		type:"get",
		dataType:"jsonp",
		data:{"help":"me","to":"die"},
		callback:"123",
		beforeSend:function(){
		},
		success:function(data){
			console.log(data)
			var list="";
			data.names.forEach(function(item,index,array){
				list=list+"<li>"+item+"</li>";
			});
			document.getElementById('name-list').innerHTML=list;
		},
		fail:function(ex){
			console.log(ex);
		}
	});
}