window.onload=function(){
		Ajax.init({
		url:"http://localhost:8080/AjaxCROSTest/data.json",
		type:"get",
		dataType:"jsonp",
		data:{"help":"me","to":"die"},
		callback:"callback",
			time:"1000",
		beforeSend:function(){
			//...
		},
		success:function(data){
			//...
		},
		fail:function(ex){
			console.log(ex);
		}
	});
}